// Product detail data — per series
const PRODUCTS = {
  AX: {
    code: 'AX',
    name: 'AX · IndoorFine',
    tagline: { tr: 'Mikro-pitch netlik.', en: 'Micro-pitch clarity.' },
    sub: { tr: 'Kontrol odaları, kurumsal lobiler ve executive alanlar için COB teknolojili mikro pixel-pitch çözüm.', en: 'COB-based micro pixel-pitch solution for control rooms, corporate lobbies and executive spaces.' },
    color: '#E6007E',
    accent2: '#FF4DA8',
    pitchRange: '0.9 – 1.5 mm',
    pitches: [0.9, 1.2, 1.5],
    brightness: '600 nit',
    mtbf: '100.000 saat',
    env: { tr: 'İç mekan · Mikro-pitch', en: 'Indoor · Micro-pitch' },
    ideal: {
      tr: ['Kontrol odası', 'Kurumsal lobi', 'Executive toplantı', 'Yönetim odası', 'Showroom'],
      en: ['Control room', 'Corporate lobby', 'Executive meeting', 'Boardroom', 'Showroom'],
    },
    features: [
      { tr: ['COB enkapsülasyon', 'Chip-on-Board teknolojisi ile darbeye, toza ve neme karşı benzersiz dayanıklılık. Parıldama yok.'], en: ['COB encapsulation', 'Chip-on-Board technology delivers unmatched resistance to impact, dust and moisture. No flickering.'] },
      { tr: ['16-bit renk işleme', 'HDR10, DCI-P3 %98 renk gamı. Broadcast ve film için kalibre edilebilir.'], en: ['16-bit color processing', 'HDR10, 98% DCI-P3 gamut. Calibrated for broadcast and film.'] },
      { tr: ['Ön servis', 'Modül bazlı ön servis — arkadan erişim gerekmez, duvar montajına uygun.'], en: ['Front service', 'Module-level front service — no rear access needed, ideal for wall mounting.'] },
      { tr: ['3840 Hz refresh', 'Flicker-free kamera çekimi için yüksek refresh rate.'], en: ['3840 Hz refresh', 'Flicker-free camera capture with high refresh rate.'] },
    ],
    specs: {
      tr: [
        ['Pixel pitch', '0.9 / 1.2 / 1.5 mm'],
        ['Parlaklık', '600 nit'],
        ['Refresh rate', '3840 Hz'],
        ['Renk derinliği', '16-bit'],
        ['Kontrast', '15.000:1'],
        ['Görüş açısı (y/d)', '160° / 160°'],
        ['Modül boyutu', '500 × 500 mm'],
        ['Modül ağırlığı', '7.5 kg'],
        ['Güç tüketimi (ort.)', '90 W/m²'],
        ['Güç tüketimi (maks.)', '720 W/m²'],
        ['IP koruması', 'IP30 ön / IP20 arka'],
        ['Servis', 'Ön servis (magnetik)'],
        ['Çalışma sıcaklığı', '-10°C – +45°C'],
        ['Sertifikalar', 'CE, FCC, RoHS, TSE'],
        ['MTBF', '100.000 saat'],
      ],
      en: [
        ['Pixel pitch', '0.9 / 1.2 / 1.5 mm'],
        ['Brightness', '600 nit'],
        ['Refresh rate', '3840 Hz'],
        ['Color depth', '16-bit'],
        ['Contrast', '15,000:1'],
        ['Viewing angle (h/v)', '160° / 160°'],
        ['Module size', '500 × 500 mm'],
        ['Module weight', '7.5 kg'],
        ['Power (avg.)', '90 W/m²'],
        ['Power (max)', '720 W/m²'],
        ['IP rating', 'IP30 front / IP20 rear'],
        ['Service', 'Front (magnetic)'],
        ['Operating temp', '-10°C – +45°C'],
        ['Certifications', 'CE, FCC, RoHS, TSE'],
        ['MTBF', '100,000 hours'],
      ],
    },
    modW: 500, modH: 500, resW: 416, resH: 416, weightPerMod: 7.5, powerPerMod: 180,
  },
  BX: {
    code: 'BX',
    name: 'BX · Broadcast',
    tagline: { tr: 'Broadcast ve XR için doğdu.', en: 'Born for broadcast and XR.' },
    sub: { tr: 'Kamera-uyumlu, flicker-free broadcast panelleri. Unreal Engine entegrasyonu ile XR sanal set.', en: 'Camera-matched, flicker-free broadcast panels. Unreal Engine integration for XR virtual sets.' },
    color: '#00E5FF',
    accent2: '#4DEDFF',
    pitchRange: '1.2 – 1.9 mm',
    pitches: [1.2, 1.5, 1.9],
    brightness: '1500 nit',
    mtbf: '100.000 saat',
    env: { tr: 'Stüdyo · XR / VP', en: 'Studio · XR / VP' },
    ideal: {
      tr: ['Broadcast stüdyo', 'Sanal set (XR)', 'Film prodüksiyon', 'Haber stüdyosu', 'Podcast stüdyo'],
      en: ['Broadcast studio', 'Virtual set (XR)', 'Film production', 'News studio', 'Podcast studio'],
    },
    features: [
      { tr: ['Kamera-uyumlu', '7680 Hz refresh ve genlikte tarama ile kamera shutter uyumu. Moire yok.'], en: ['Camera-matched', '7680 Hz refresh with phase-locked scan. No moire, no flicker.'] },
      { tr: ['XR / VP hazır', 'Unreal Engine, Disguise, Pixotope ile direkt entegrasyon. Genlock + Tracking desteği.'], en: ['XR / VP ready', 'Direct integration with Unreal Engine, Disguise, Pixotope. Genlock + Tracking support.'] },
      { tr: ['CBSF teknolojisi', 'Color Brightness Shift Free — tüm görüş açılarında parlaklık ve renk tutarlılığı.'], en: ['CBSF technology', 'Color Brightness Shift Free — consistent brightness and color across all angles.'] },
      { tr: ['Yüksek parlaklık', '1500 nit — ambient ışığa rağmen derin siyah ve sinematik kontrast.'], en: ['High brightness', '1500 nit — deep blacks and cinematic contrast under ambient lighting.'] },
    ],
    specs: {
      tr: [
        ['Pixel pitch', '1.2 / 1.5 / 1.9 mm'],
        ['Parlaklık', '1500 nit'],
        ['Refresh rate', '7680 Hz'],
        ['Renk derinliği', '16-bit'],
        ['Kontrast', '20.000:1'],
        ['Görüş açısı (y/d)', '160° / 160°'],
        ['Modül boyutu', '500 × 500 mm'],
        ['Modül ağırlığı', '7.8 kg'],
        ['Güç tüketimi (ort.)', '180 W/m²'],
        ['Güç tüketimi (maks.)', '840 W/m²'],
        ['Özellikler', 'Genlock, Tracking, CBSF'],
        ['IP koruması', 'IP30'],
        ['Servis', 'Ön servis'],
        ['Çalışma sıcaklığı', '-10°C – +45°C'],
        ['MTBF', '100.000 saat'],
      ],
      en: [
        ['Pixel pitch', '1.2 / 1.5 / 1.9 mm'],
        ['Brightness', '1500 nit'],
        ['Refresh rate', '7680 Hz'],
        ['Color depth', '16-bit'],
        ['Contrast', '20,000:1'],
        ['Viewing angle (h/v)', '160° / 160°'],
        ['Module size', '500 × 500 mm'],
        ['Module weight', '7.8 kg'],
        ['Power (avg.)', '180 W/m²'],
        ['Power (max)', '840 W/m²'],
        ['Features', 'Genlock, Tracking, CBSF'],
        ['IP rating', 'IP30'],
        ['Service', 'Front'],
        ['Operating temp', '-10°C – +45°C'],
        ['MTBF', '100,000 hours'],
      ],
    },
    modW: 500, modH: 500, resW: 333, resH: 333, weightPerMod: 7.8, powerPerMod: 210,
  },
  CX: {
    code: 'CX',
    name: 'CX · Corporate',
    tagline: { tr: 'Kurumsal için dengeli.', en: 'Balanced for corporate.' },
    sub: { tr: 'Auditorium, konferans salonu ve toplantı odaları için 16:9 standart LED video duvarı.', en: '16:9 native LED video wall for auditoriums, conference halls and meeting rooms.' },
    color: '#6A5ACD',
    accent2: '#9A8AEE',
    pitchRange: '1.5 – 2.5 mm',
    pitches: [1.5, 1.9, 2.5],
    brightness: '800 nit',
    mtbf: '80.000 saat',
    env: { tr: 'İç mekan · Standart', en: 'Indoor · Standard' },
    ideal: {
      tr: ['Auditorium', 'Konferans salonu', 'Toplantı odası', 'Eğitim salonu', 'Lobi'],
      en: ['Auditorium', 'Conference hall', 'Meeting room', 'Training hall', 'Lobby'],
    },
    features: [
      { tr: ['16:9 native', 'Modül geometrisi 16:9 için optimize — bezelsiz sinema deneyimi.'], en: ['16:9 native', 'Module geometry optimized for 16:9 — bezel-free cinema experience.'] },
      { tr: ['Sessiz çalışma', 'Fansız, pasif soğutma. 0 dB. Konferans salonları için ideal.'], en: ['Silent operation', 'Fanless, passive cooling. 0 dB. Ideal for conference halls.'] },
      { tr: ['Düşük güç', 'Common-cathode sürücüler geleneksel LED\'e göre %40 daha az enerji.'], en: ['Low power', 'Common-cathode drivers cut power by 40% vs traditional LED.'] },
      { tr: ['Ön / arka servis', 'Duvar montajı ve rack montajı için çift yönlü servis.'], en: ['Front / rear service', 'Dual-access service for wall and rack mounting.'] },
    ],
    specs: {
      tr: [
        ['Pixel pitch', '1.5 / 1.9 / 2.5 mm'],
        ['Parlaklık', '800 nit'],
        ['Refresh rate', '3840 Hz'],
        ['Renk derinliği', '14-bit'],
        ['Kontrast', '10.000:1'],
        ['Görüş açısı (y/d)', '160° / 160°'],
        ['Modül boyutu', '500 × 500 mm'],
        ['Modül ağırlığı', '7.2 kg'],
        ['Güç tüketimi (ort.)', '95 W/m²'],
        ['Güç tüketimi (maks.)', '760 W/m²'],
        ['Akustik', '0 dB (fansız)'],
        ['IP koruması', 'IP30'],
        ['Servis', 'Ön / arka'],
        ['Sertifikalar', 'CE, FCC, RoHS'],
        ['MTBF', '80.000 saat'],
      ],
      en: [
        ['Pixel pitch', '1.5 / 1.9 / 2.5 mm'],
        ['Brightness', '800 nit'],
        ['Refresh rate', '3840 Hz'],
        ['Color depth', '14-bit'],
        ['Contrast', '10,000:1'],
        ['Viewing angle (h/v)', '160° / 160°'],
        ['Module size', '500 × 500 mm'],
        ['Module weight', '7.2 kg'],
        ['Power (avg.)', '95 W/m²'],
        ['Power (max)', '760 W/m²'],
        ['Acoustic', '0 dB (fanless)'],
        ['IP rating', 'IP30'],
        ['Service', 'Front / rear'],
        ['Certifications', 'CE, FCC, RoHS'],
        ['MTBF', '80,000 hours'],
      ],
    },
    modW: 500, modH: 500, resW: 263, resH: 263, weightPerMod: 7.2, powerPerMod: 190,
  },
  DX: {
    code: 'DX',
    name: 'DX · Stage',
    tagline: { tr: 'Sahnede dayanıklı.', en: 'Built for the stage.' },
    sub: { tr: 'Touring standardında, hafif kiralama serisi. Konser, festival ve sahne için hızlı montaj.', en: 'Touring-grade rental series. Fast deployment for concerts, festivals and stages.' },
    color: '#FF6A00',
    accent2: '#FF9A40',
    pitchRange: '2.6 – 3.9 mm',
    pitches: [2.6, 2.9, 3.9],
    brightness: '4500 nit',
    mtbf: '60.000 saat',
    env: { tr: 'Etkinlik · Kiralama', en: 'Event · Rental' },
    ideal: {
      tr: ['Konser sahnesi', 'Festival', 'Arena etkinlik', 'Fuar standı', 'Touring'],
      en: ['Concert stage', 'Festival', 'Arena event', 'Trade show', 'Touring'],
    },
    features: [
      { tr: ['Hafif kasa', 'Modül başı 6.5 kg. Hızlı kurulum ve sökülmeye optimize.'], en: ['Lightweight case', '6.5 kg per module. Optimized for fast setup and teardown.'] },
      { tr: ['IP54 (ön)', 'Dış etkinlik koşullarına dayanıklı. Yağmur ve toza karşı koruma.'], en: ['IP54 (front)', 'Weatherproof for outdoor events. Rain and dust resistant.'] },
      { tr: ['Flybar sistemi', 'Standart flybar ile hızlı asma. Touring case içinde 6 modül.'], en: ['Flybar system', 'Fast rigging with standard flybar. 6 modules per touring case.'] },
      { tr: ['4500 nit parlaklık', 'Açık havada bile net görüntü. Auto-brightness sensor dahil.'], en: ['4500 nit brightness', 'Clear visibility even outdoors. Auto-brightness sensor included.'] },
    ],
    specs: {
      tr: [
        ['Pixel pitch', '2.6 / 2.9 / 3.9 mm'],
        ['Parlaklık', '4500 nit'],
        ['Refresh rate', '3840 Hz'],
        ['Renk derinliği', '14-bit'],
        ['Görüş açısı (y/d)', '140° / 140°'],
        ['Modül boyutu', '500 × 500 mm'],
        ['Modül ağırlığı', '6.5 kg'],
        ['Güç tüketimi (maks.)', '1280 W/m²'],
        ['IP koruması', 'IP54 (ön) / IP43 (arka)'],
        ['Kasa', 'Touring road case, 6 modül'],
        ['Rigging', 'Flybar + quick-lock'],
        ['Servis', 'Ön servis'],
        ['Çalışma sıcaklığı', '-20°C – +50°C'],
        ['Sertifikalar', 'CE, FCC'],
        ['MTBF', '60.000 saat'],
      ],
      en: [
        ['Pixel pitch', '2.6 / 2.9 / 3.9 mm'],
        ['Brightness', '4500 nit'],
        ['Refresh rate', '3840 Hz'],
        ['Color depth', '14-bit'],
        ['Viewing angle (h/v)', '140° / 140°'],
        ['Module size', '500 × 500 mm'],
        ['Module weight', '6.5 kg'],
        ['Power (max)', '1280 W/m²'],
        ['IP rating', 'IP54 (front) / IP43 (rear)'],
        ['Case', 'Touring road case, 6 modules'],
        ['Rigging', 'Flybar + quick-lock'],
        ['Service', 'Front'],
        ['Operating temp', '-20°C – +50°C'],
        ['Certifications', 'CE, FCC'],
        ['MTBF', '60,000 hours'],
      ],
    },
    modW: 500, modH: 500, resW: 128, resH: 128, weightPerMod: 6.5, powerPerMod: 320,
  },
  EX: {
    code: 'EX',
    name: 'EX · Outdoor',
    tagline: { tr: 'Dışarıda bile parlak.', en: 'Bright even outdoors.' },
    sub: { tr: 'Digital signage, DOOH ve bina cephesi için IP65 korumalı outdoor LED serisi.', en: 'IP65-rated outdoor LED series for digital signage, DOOH and building facades.' },
    color: '#FFB020',
    accent2: '#FFCC6A',
    pitchRange: '4.0 – 10 mm',
    pitches: [4, 6, 8, 10],
    brightness: '6000 nit',
    mtbf: '60.000 saat',
    env: { tr: 'Dış mekan', en: 'Outdoor' },
    ideal: {
      tr: ['Digital signage', 'DOOH reklam', 'Bina cephesi', 'Meydan ekranı', 'Stadyum'],
      en: ['Digital signage', 'DOOH advertising', 'Building facade', 'Plaza display', 'Stadium'],
    },
    features: [
      { tr: ['IP65 koruma', 'Yağmur, toz ve yüksek neme karşı tam koruma. Her koşulda çalışır.'], en: ['IP65 rated', 'Full protection against rain, dust and humidity. Works in all conditions.'] },
      { tr: ['6000 nit parlaklık', 'Direkt güneş ışığı altında bile net okunabilir. Otomatik parlaklık ayarı.'], en: ['6000 nit brightness', 'Readable under direct sunlight. Auto brightness control.'] },
      { tr: ['UV korumalı', 'Solmayan renkler, UV filtreli ön yüzey. 10 yıl renk garantisi.'], en: ['UV resistant', 'Fade-proof colors, UV-filtered front. 10-year color warranty.'] },
      { tr: ['Geniş sıcaklık aralığı', '-40°C ile +60°C arası çalışabilir. İç ısıtma/soğutma dahil.'], en: ['Wide temp range', 'Operates from -40°C to +60°C. Internal heating/cooling included.'] },
    ],
    specs: {
      tr: [
        ['Pixel pitch', '4 / 6 / 8 / 10 mm'],
        ['Parlaklık', '6000 nit'],
        ['Refresh rate', '1920 Hz'],
        ['Renk derinliği', '14-bit'],
        ['Görüş açısı (y/d)', '140° / 120°'],
        ['Modül boyutu', '960 × 960 mm'],
        ['Modül ağırlığı', '38 kg'],
        ['Güç tüketimi (maks.)', '900 W/m²'],
        ['IP koruması', 'IP65 (ön/arka)'],
        ['UV koruması', 'Evet, ön yüzeyde'],
        ['Servis', 'Arka servis'],
        ['Çalışma sıcaklığı', '-40°C – +60°C'],
        ['Sertifikalar', 'CE, FCC, IP65, IK10'],
        ['Garanti', '5 yıl donanım, 10 yıl renk'],
        ['MTBF', '60.000 saat'],
      ],
      en: [
        ['Pixel pitch', '4 / 6 / 8 / 10 mm'],
        ['Brightness', '6000 nit'],
        ['Refresh rate', '1920 Hz'],
        ['Color depth', '14-bit'],
        ['Viewing angle (h/v)', '140° / 120°'],
        ['Module size', '960 × 960 mm'],
        ['Module weight', '38 kg'],
        ['Power (max)', '900 W/m²'],
        ['IP rating', 'IP65 (front/rear)'],
        ['UV resistance', 'Yes, front surface'],
        ['Service', 'Rear'],
        ['Operating temp', '-40°C – +60°C'],
        ['Certifications', 'CE, FCC, IP65, IK10'],
        ['Warranty', '5-year hardware, 10-year color'],
        ['MTBF', '60,000 hours'],
      ],
    },
    modW: 960, modH: 960, resW: 160, resH: 160, weightPerMod: 38, powerPerMod: 420,
  },
  FX: {
    code: 'FX',
    name: 'FX · Creative',
    tagline: { tr: 'Her forma uyar.', en: 'Any shape imaginable.' },
    sub: { tr: 'Esnek modüller ile sütun, kavis, tavan ve zemin uygulamaları. Creative LED yapıları.', en: 'Flexible modules for columns, curves, ceilings and floors. Creative LED structures.' },
    color: '#9333EA',
    accent2: '#B76AF2',
    pitchRange: '1.9 – 6.0 mm',
    pitches: [1.9, 2.6, 3.9, 6.0],
    brightness: '800 nit',
    mtbf: '80.000 saat',
    env: { tr: 'Flexible · Shaped', en: 'Flexible · Shaped' },
    ideal: {
      tr: ['Sütun sarma', 'Kavisli duvar', 'Tavan ekranı', 'LED zemin', 'Heykel'],
      en: ['Column wrap', 'Curved wall', 'Ceiling display', 'LED floor', 'Sculpture'],
    },
    features: [
      { tr: ['Esnek modül', 'İçe / dışa 90° bükülebilir modüller. Silindirik sütunlar için ideal.'], en: ['Flex module', 'Modules bend 90° inward/outward. Ideal for cylindrical columns.'] },
      { tr: ['Üzerine basılabilir', 'LED floor varyantı 2000 kg/m² yüke dayanıklı. Cam yüzey koruması.'], en: ['Walkable', 'LED floor variant withstands 2000 kg/m². Glass surface protection.'] },
      { tr: ['Hızlı bağlantı', 'Manyetik / mekanik quick-lock ile özel formlara hızlı montaj.'], en: ['Quick connect', 'Magnetic / mechanical quick-lock for fast custom form assembly.'] },
      { tr: ['Özel form desteği', 'Tasarım ekibimiz ile silindirik, spherik, dalga veya logo formları üretiriz.'], en: ['Custom form support', 'Our design team produces cylindrical, spherical, wave or logo forms.'] },
    ],
    specs: {
      tr: [
        ['Pixel pitch', '1.9 / 2.6 / 3.9 / 6 mm'],
        ['Parlaklık', '800 nit'],
        ['Refresh rate', '3840 Hz'],
        ['Renk derinliği', '14-bit'],
        ['Görüş açısı (y/d)', '160° / 140°'],
        ['Modül boyutu', '500 × 500 mm'],
        ['Modül ağırlığı', '7.0 kg'],
        ['Bükülme açısı', '±90° (iç/dış)'],
        ['Güç tüketimi (maks.)', '880 W/m²'],
        ['IP koruması', 'IP31'],
        ['Zemin yükü', '2000 kg/m² (zemin varyantı)'],
        ['Servis', 'Ön servis'],
        ['Form tipleri', 'Silindir, kavis, sphere, custom'],
        ['Sertifikalar', 'CE, FCC, RoHS'],
        ['MTBF', '80.000 saat'],
      ],
      en: [
        ['Pixel pitch', '1.9 / 2.6 / 3.9 / 6 mm'],
        ['Brightness', '800 nit'],
        ['Refresh rate', '3840 Hz'],
        ['Color depth', '14-bit'],
        ['Viewing angle (h/v)', '160° / 140°'],
        ['Module size', '500 × 500 mm'],
        ['Module weight', '7.0 kg'],
        ['Bend angle', '±90° (in/out)'],
        ['Power (max)', '880 W/m²'],
        ['IP rating', 'IP31'],
        ['Floor load', '2000 kg/m² (floor variant)'],
        ['Service', 'Front'],
        ['Form types', 'Cylinder, curve, sphere, custom'],
        ['Certifications', 'CE, FCC, RoHS'],
        ['MTBF', '80,000 hours'],
      ],
    },
    modW: 500, modH: 500, resW: 192, resH: 192, weightPerMod: 7.0, powerPerMod: 220,
  },
};

// Product-page i18n
const P_I18N = {
  tr: {
    backToAll: '← Tüm seriler',
    downloadPDF: 'Broşürü PDF indir',
    requestQuote: 'Teklif Al',
    overview: 'Genel Bakış',
    features: 'Öne Çıkan Özellikler',
    configurator: 'Bu Seri İçin Konfigüratör',
    configuratorLead: 'Modül sayısını seçin — boyut, çözünürlük, güç ve ağırlık otomatik hesaplanır.',
    specs: 'Teknik Spesifikasyonlar',
    specsLead: 'Detaylı teknik veri. Ek bilgi için broşürü indirin.',
    applications: 'Önerilen Uygulama Alanları',
    cta: 'Bu konfigürasyon için teklif al',
    brightness: 'Parlaklık',
    pitch: 'Pixel pitch',
    mtbf: 'MTBF',
    env: 'Ortam',
    pitchSelect: 'Pitch varyantı',
    cols: 'Yatay modül',
    rows: 'Dikey modül',
    size: 'Toplam boyut',
    res: 'Çözünürlük',
    ratio: 'En-boy',
    modules: 'Modül',
    power: 'Güç',
    weight: 'Ağırlık',
  },
  en: {
    backToAll: '← All series',
    downloadPDF: 'Download Brochure PDF',
    requestQuote: 'Request Quote',
    overview: 'Overview',
    features: 'Key Features',
    configurator: 'Configurator for this Series',
    configuratorLead: 'Choose module count — size, resolution, power and weight auto-calculate.',
    specs: 'Technical Specifications',
    specsLead: 'Detailed technical data. Download the brochure for more.',
    applications: 'Recommended Applications',
    cta: 'Request quote for this configuration',
    brightness: 'Brightness',
    pitch: 'Pixel pitch',
    mtbf: 'MTBF',
    env: 'Environment',
    pitchSelect: 'Pitch variant',
    cols: 'Horizontal modules',
    rows: 'Vertical modules',
    size: 'Total size',
    res: 'Resolution',
    ratio: 'Aspect',
    modules: 'Modules',
    power: 'Power',
    weight: 'Weight',
  },
};

window.PRODUCTS = PRODUCTS;
window.P_I18N = P_I18N;
